# Generated by Django 2.2 on 2020-08-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work', '0003_auto_20200816_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.Kontakt')),
            ],
        ),
    ]
