# Generated by Django 2.2 on 2020-08-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_auto_20200816_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'verbose_name': 'Статус Заказа', 'verbose_name_plural': 'Статус Заказов'},
        ),
    ]
