# Generated by Django 2.2 on 2020-08-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kontakt',
            name='midl_name',
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='added_user',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='имя и отчество'),
        ),
    ]
