# Generated by Django 2.2 on 2020-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200815_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='companiName',
            field=models.CharField(max_length=40, verbose_name='название компании'),
        ),
    ]
