# Generated by Django 2.2 on 2020-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='title2',
            field=models.CharField(default=1, max_length=200, unique=True, verbose_name='Запись менеджера о погоде'),
            preserve_default=False,
        ),
    ]
