# Generated by Django 2.2 on 2020-08-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_title2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'verbose_name': 'Воронку', 'verbose_name_plural': 'Воронка'},
        ),
    ]
