# Generated by Django 2.2 on 2020-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Akt', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Акт')),
                ('schet', models.CharField(blank=True, max_length=200, null=True, verbose_name='Счет')),
                ('nakladnay', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Накладная')),
                ('doverinost', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Довериность')),
                ('bussnproposal', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Комерческое предложение')),
                ('podrad', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Договор подряда')),
                ('postavka', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Договор поставки')),
                ('uslugi', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Договор оказания услуг')),
                ('universdok', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Универсальний предаточний документ')),
                ('listdoks', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Список документов')),
            ],
        ),
    ]
