# Generated by Django 2.2 on 2020-08-16 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'verbose_name': 'Документи', 'verbose_name_plural': 'Документ'},
        ),
    ]
