# Generated by Django 2.2 on 2020-08-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20200816_2052'),
        ('documents', '0002_auto_20200816_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='kanban2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='work.Kontakt', verbose_name='наследование конт.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='doverinost',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Довереность'),
        ),
    ]
